version: '3.8'

services:
  PostgreSQL:
    restart: always
    image: postgres:12.0-alpine
    hostname: postgres
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    hostname: adminer
    container_name: Adminer
    restart: always
    ports:
      - "8080:8080"

  Redis:
    restart: always
    image: redis:latest
    hostname: redis
    container_name: Redis
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false

volumes:
  db-data:
    driver: local