version: '3.4'
services:
  net_worth_calculator:
    restart: always
    image: net-worth-calculator:latest
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - DEBUG=true
      - SC_PASSWORD_SALT=06!grsnxXG0d*Pj496p6fuA*o
      - SC_APP_ENV=test
