version: '3.8'

services:
  net_worth_calculator:
    image: net-worth-calculator:latest
    container_name: net-worth-calculator
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=true
      - NWC_APP_ENV=test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=networth
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./../modules/core/src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false

volumes:
  db-data:
    driver: local

