version: '3.8'

services:
  net_worth_calculator:
    image: net-worth-calculator:latest
    container_name: net-worth-calculator
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=true
      - NWC_APP_ENV=test

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - "8686:8080"

  postgres:
    image: postgres:12.0-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
    volumes:
      - ./../init:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false

volumes:
  db-data:
    driver: local

