version: '3.8'

services:
  net_worth_calculator:
    image: net-worth-calculator:latest
    container_name: net-worth-calculator
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=true
      - SC_APP_ENV=test
    networks:
      - mynetwork

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_DB=networth
      - POSTGRES_USER=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./modules/core/src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - DEBUG=false
    networks:
      - mynetwork

volumes:
  db-data:
    driver: local

networks:
  mynetwork:
    driver: "bridge"
