CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  salt VARCHAR NOT NULL,
  role VARCHAR NOT NULL
);

CREATE TABLE assets (
  id SERIAL PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL
);
